module.exports = Object.freeze({
    Cart: "Cart",
    CartItem: "CartItem",
    Category: "Category",
    CartItemEditReq: "CartItemEditReq",
    CartEditReqStatus: "CartEditReqStatus",
    Color: "Color",
    DesignUpload: "DesignUpload",
    Drive: "Drive",
    FileUpload: "FileUpload",
    Marketing: "Marketing",
    Permission: "Permission",
    Tag: "Tag",
    User: "User",
    Variation: "Variation",
})